### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by gofornaman** [rhnvrm/labeled-tweet-generator#5]
When I try to exec > python app.py , it throws this error

Traceback (most recent call last):
  File "app.py", line 8, in <module>
    api = TwitterClient('@Sirajology')
  File "/home/naman/Desktop/labeled-tweet-generator/twitter.py", line 14, in __init__
    consumer_key = os.environ['TW9Jd0pnZll4NUrVGsKDu7hdc']
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'TW9Jd0pnZll4NUrVGsKDu7hdc'

Where did I do wrong? Thanks

**Comment by rhnvrm** [comment]
It should be:
`consumer_key = 'TW9Jd0pnZll4NUrVGsKDu7hdc'`

or set an Environment variable locally.

**Comment by gofornaman** [comment]
Yes, I tried that as well. It's running but not displaying the tweets. Is it necessary to run it on Heroku?

![123](https://user-images.githubusercontent.com/17682245/33517109-feb59a7e-d7a3-11e7-97d3-4a61f94a2a34.png)

**Comment by rhnvrm** [comment]
@warmachine0609 Not at all, check the logs in the terminal or your browsers javascript console. There must be some other error or warning.

**Comment by gofornaman** [comment]
![err](https://user-images.githubusercontent.com/17682245/33526447-d6d27fe4-d867-11e7-8dcc-f15f401947dd.png)

Yes, how do I fix it?

**Comment by rhnvrm** [comment]
@warmachine0609 and what is the error on your terminal?
